name: CICD

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        run: echo "Sai@12345" | docker login -u "sainath521" --password-stdin

      - name: Build Docker Image
        run: docker build -t sainath521/akkio-frontend .

      - name: Publish Image to Docker Hub
        run: docker push sainath521/akkio-frontend:latest   

  deploy: 
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Install SSH Client
        run: sudo apt-get install -y openssh-client

      - name: Add SSH Key
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      - name: Deploy to EC2
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@47.129.187.19 << 'EOF'
            sudo bash -c "
              # Pull the latest Docker image
              docker pull sainath521/akkio-frontend:latest

              # Stop and remove the old Docker container if it exists
              docker stop akkio-frontend-container || true
              docker rm akkio-frontend-container || true

              # Run the new Docker container on port 3000
              docker run -d -p 3000:3000 --name akkio-frontend-container sainath521/akkio-frontend:latest
            "
          EOF
